# name: Build & Push Docker Image to container image registry

# on:
#   release:
#     types: [created]
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
#     paths:
#       - "Dockerfile"

# jobs:
#   docker:
#     uses: stegripe/workflows/.github/workflows/docker-build.yml@main
#     secrets: inherit
