name: Lint code and compile setup script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  test:
    uses: stegripe/workflows/.github/workflows/pnpm-lint-and-test.yml@main
    secrets: inherit
