name: Lint code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    uses: stegripe/workflows/.github/workflows/pnpm-lint.yaml@main
    secrets: inherit
